# Generated by Django 5.2.1 on 2025-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='you@example.com', max_length=100, unique=True, verbose_name='Електронна пошта'),
        ),
    ]
